functionsDirectory = "/home/ubuntu/clipauto_work/clipauto-api/netlify/functions"
functionsDirectoryOrigin = "config-v1"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "/home/ubuntu/clipauto_work/clipauto-api/public"
publishOrigin = "config"
functions = "/home/ubuntu/clipauto_work/clipauto-api/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[redirects]]
from = "/api/channels/*"
to = "/.netlify/functions/channels/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/channels"
to = "/.netlify/functions/channels"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/clips/*"
to = "/.netlify/functions/clips/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/clips"
to = "/.netlify/functions/clips"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/auth/*"
to = "/.netlify/functions/auth/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/trending"
to = "/.netlify/functions/trending"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/platforms"
to = "/.netlify/functions/platforms"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]